# -*- coding: utf-8 -*-
""" Names of vychova attributes.

First empty string is due to python counting from 0.
"""

vychova_strings = ["",
                   "I Podurovnova 0.7",
                   "I Podurovnova 0.8",
                   "I Podurovnova 0.9",
                   "I Neutralna 0.7",
                   "I Neutralna 0.8",
                   "I Neutralna 0.9",
                   "I Urovnova 0.7",
                   "I Urovnova 0.8",
                   "I Urovnova 0.9",
                   "I Cielove stromy 7m - 1",
                   "I Cielove stromy 7m - 2",
                   "I Cielove stromy 7m - 3",
                   "I Cielove stromy 8m - 1",
                   "I Cielove stromy 8m - 2",
                   "I Cielove stromy 8m - 3",
                   "I Cielove stromy 8m - 1",
                   "I Cielove stromy 8m - 2",
                   "I Cielove stromy 8m - 3",
                   "II Podurovnova 0.7",
                   "II Podurovnova 0.8",
                   "II Podurovnova 0.9",
                   "II Neutralna 0.7",
                   "II Neutralna 0.8",
                   "II Neutralna 0.9",
                   "II Urovnova 0.7",
                   "II Urovnova 0.8",
                   "II Urovnova 0.9",
                   "II Cielove stromy 7m - 1",
                   "II Cielove stromy 7m - 2",
                   "II Cielove stromy 7m - 3",
                   "II Cielove stromy 8m - 1",
                   "II Cielove stromy 8m - 2",
                   "II Cielove stromy 8m - 3",
                   "II Cielove stromy 8m - 1",
                   "II Cielove stromy 8m - 2",
                   "II Cielove stromy 8m - 3",
                  ]
